name: df_string_example
homepage: https://dev-cetera.com/
publish_to: none
version: 0.1.0
environment:
  sdk: ">=3.5.0 <4.0.0"
dependencies:
  df_string:
    path: ..
dev_dependencies:
  lints: ^6.0.0
