##.title
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##
## Copyright © dev-cetera.com & contributors.
##
## The use of this source code is governed by an MIT-style license described in
## the LICENSE file located in this project's root directory.
##
## See: https://opensource.org/license/mit
##
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##.title~

name: df_string
homepage: https://dev-cetera.com/
repository: https://github.com/robmllze/df_string
funding:
  - https://www.buymeacoffee.com/dev_cetera
  - https://www.patreon.com/c/robelator
  - https://github.com/sponsors/robelator
description: A package designed to extend Dart strings by offering additional functionality.
version: 0.4.0
topics:
  - dart
  - json
  - string
  - utility
  - tool

## -----------------------------------------------------------------------------

environment:
  sdk: ">=3.5.0 <4.0.0"

## -----------------------------------------------------------------------------

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.2

